remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: ApoFakt Resources
description: Here you can find the ApoFAKT related resources, e.g. the latest ApoFakt release notes.
