remote_theme: PrivatCode/github-pages-jekyll-theme
plugins:
- jekyll-remote-theme

title: ApoFAKT
description: Hier finden Sie die ApoFAKT Informationen, u. a. die aktuellen Anmerkungen zu der neuesten Programmversion.
color-scheme: auto
hide_project_page: true
contents-header: Inhaltsverzeichnis
project-maintenance-footer: Dieses Projekt wird verwaltet von
hide_project_footer: true

navigation:
  - name: Release Notes
    link: ./release_notes
    sublist:
