remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
- jekyll-remote-theme

title: ApoFakt Resources
description: Here you can find the ApoFAKT related resources, e.g. the latest ApoFakt release notes.
color-scheme: auto
