remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
- jekyll-remote-theme

title: ApoFakt Resources
description: Here you can find the ApoFAKT related resources, e.g. the latest ApoFakt release notes.
color-scheme: auto
navigation:
  - name: Version 5.3.11.0 (x)
    link: ./release_notes.md#version-53110-x
  - name: Version 5.3.10.1 (x)
    link: ./release_notes.md#version-53101-x
  - name: Version 5.3.10.0 (12.10.2023)
    link: ./release_notes.md#version-53100-12102023
