remote_theme: PrivatCode/github-pages-jekyll-theme
plugins:
- jekyll-remote-theme

title: ApoFAKT
description: Hier finden Sie die ApoFAKT Informationen, u. a. die aktuellen Anmerkungen zu der neuesten Programmversion.
color-scheme: auto
hide_project_page: true
contents-header: Inhaltsverzeichnis
project-maintenance-footer: Dieses Projekt wird verwaltet von
hide_project_footer: true
logo: ./af_logo.png

navigation:
  - name: Release Notes
    link: ./release_notes
    sublist:
      - name: v5.3.13.1 (befindet sich derzeit im Test)
        link: ./release_notes#version-53131-befindet-sich-derzeit-im-test
      - name: v5.3.13.0 (öff. am 09.04.2024)
        link: ./release_notes#version-53130-öff-am-09042024
      - name: v5.3.12.0 (öff. am 15.02.2024)
        link: ./release_notes#version-53120-öff-am-15022024
      - name: v5.3.11.2 (öff. am  22.01.2024)
        link: ./release_notes#version-53112-öff-am--22012024
      - name: v5.3.11.1 (öff. am  09.01.2024)
        link: ./release_notes#version-53111-öff-am--09012024
      - name: v5.3.11.0 (öff. am 29.11.2023)
        link: ./release_notes#version-53110-öff-am-29112023
      - name: v5.3.10.1 (öff. am 06.11.2023)
        link: ./release_notes#version-53101-öff-am-06112023
      - name: v5.3.10.0 (öff. am 12.10.2023)
        link: ./release_notes#version-53100-öff-am-12102023
      - name: v5.3.9.1 (öff. am 06.09.2023)
        link: ./release_notes#version-5391-öff-am-06092023
      - name: v5.3.9 (öff. am 21.08.2023)
        link: ./release_notes#version-539-öff-am-21082023
      - name: v5.3.8.4 (öff. am 24.07.2023)
        link: ./release_notes#version-5384-öff-am-24072023
      - name: v5.3.8.3 (öff. am 14.07.2023)
        link: ./release_notes#version-5383-öff-am-14072023
      - name: v5.3.8.2 (öff. am 10.07.2023)
        link: ./release_notes#version-5382-öff-am-10072023
      - name: v5.3.8.1 (öff. am 28.06.2023)
        link: ./release_notes#version-5381-öff-am-28062023
      - name: v5.3.8.0 (öff. am 15.06.2023)
        link: ./release_notes#version-5380-öff-am-15062023
